=== bhmeb/CoreJava_Projects/Core_Java_Projects2/bin/XMLDemo/EmployeeDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Root (Child+)>
<!ELEMENT Child (name,id,address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ATTLIST Child aid ID #REQUIRED>

=== bhmeb/CoreJava_Projects/Core_Java_Projects2/bin/XMLDemo/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Root SYSTEM "EmployeeDTD.dtd">

<Root>

<Child aid="FirstChild">
<name>Raj</name>	
<id>100</id>
<address>Kolkata</address>
</Child>

<Child aid="SecondChild">
<name>Aryan</name>
<id>200</id>
<address>Mumbai</address>
</Child>

</Root>
